version: '3.8'

services:
  api-financa:
    image: ghcr.io/cskuma/fincanca-autenticador:dev
    container_name: api-financa
    env_file:
      - /home/ubuntu/keycloak-docker/envs/.env
    volumes:
      - /home/ubuntu/keycloak-docker/envs/firebase-api-env:/app/credenciais:ro
    ports:
      - "8082:8080"
    restart: always
