version: "3.8"

services:
  financa-api:
    image: ghcr.io/cskuma/financa-api:latest
    container_name: financa-api
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/keycloak-docker/envs/.env
    environment:
      - CONFIG_FIREBASE=/app/credenciais/serviceAccountKey.json
    volumes:
      - /home/ubuntu/keycloak-docker/envs/firebase-api-env:/app/credenciais:ro
    restart: unless-stopped
