version: "3.8"

services:
  firebase-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu-app
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/keycloak-docker/envs/firebase-api-env:/app/envs
    environment:
      - env_firebase=/app/envs/serviceAccountKey.json
    restart: unless-stopped
