FIREBASE_CONFIG=${CONFIG_FIREBASE}
#FIREBASE_CONFIG=src/main/resources/serviceAccountKey.json


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}